/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Flikd Design (https://sketchfab.com/Flikd_Design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jedi-holocron-4843940458cb48e18fa2cc79760c0114
Title: Jedi Holocron
*/
"use client";
import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Holocron(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/jedi_holocron.glb');
  const { actions } = useAnimations(animations, group);

  // Play the animation called "Animation"
  useEffect(() => {
    if (actions.Animation) {
      actions.Animation.reset().play(); 
    }

    return () => {
      if (actions.Animation) {
        actions.Animation.stop(); 
      }
    };
  }, [actions]);

  useFrame(() => {
    group.current.rotation.y -= 0.0023;
  });

  return (
    <group ref={group} {...props} dispose={null} rotation={[0, 0, 1]} scale={[8, 8, 8]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.033}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_12" rotation={[0, Math.PI / 4, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.Gold}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.Glow}
                    skeleton={nodes.Object_20.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials.Glass}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    name="Object_22"
                    geometry={nodes.Object_22.geometry}
                    material={materials.Grey}
                    skeleton={nodes.Object_22.skeleton}
                  />
                  <group name="Cube_11_correction" rotation={[0, -Math.PI / 4, 0]}>
                    <group name="Cube_11" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/jedi_holocron.glb');

